# Generated by Django 4.1.2 on 2022-11-09 11:36

from django.db import migrations, models
import services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'null': 'Пользователь должен иметь номер телефона.', 'unique': 'Пользователь с таким номером телефона уже существует.'}, help_text="Обязательно. Максимально допустимое кол-во символов - 18. Цифры и символы '()', '+' и '_'.", max_length=12, unique=True, validators=[services.validators.PhoneNumberValidator()], verbose_name='Номер телефона'),
        ),
    ]
