# Generated by Django 4.1.2 on 2022-11-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(blank=True, error_messages={'unique': 'Пользователь с таким Telegram ID уже существует.'}, null=True, unique=True, verbose_name='Telegram ID пользователя'),
        ),
    ]
