# Generated by Django 4.1.2 on 2022-12-16 11:24

from django.db import migrations, models
import services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, error_messages={'null': 'Пользователь должен иметь номер телефона.', 'unique': 'Пользователь с таким номером телефона уже существует.'}, help_text="Обязательно. Максимально допустимое кол-во символов - 18. Цифры и символы '()', '+' и '_'.", max_length=12, unique=True, validators=[services.validators.PhoneNumberValidator()], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(blank=True, db_index=True, error_messages={'unique': 'Пользователь с таким Telegram ID уже существует.'}, null=True, unique=True, verbose_name='Telegram ID пользователя'),
        ),
    ]
