# Generated by Django 4.1.2 on 2022-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='discount',
            field=models.DecimalField(blank=True, choices=[(None, 'Укажите скидку'), (0.15, 'Первый визит'), (0.35, 'Шестой визит'), (500.0, 'Сарафан')], decimal_places=2, help_text='Необходимо указать.', max_digits=4, null=True, verbose_name='Тип скидки'),
        ),
    ]
