# Generated by Django 4.1.2 on 2022-11-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_type',
            new_name='user_type',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='qualification',
            new_name='user_type',
        ),
    ]
