# Generated by Django 4.1.2 on 2022-10-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_visit_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='service_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='tax',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Налог'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, verbose_name='Вывод по чеку'),
        ),
    ]
