# Generated by Django 4.1.2 on 2022-10-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_visit_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='discount',
            field=models.FloatField(blank=True, choices=[(None, 'Укажите скидку'), (0.15, 'Первый визит'), (0.35, 'Шестой визит'), (500.0, 'Сарафан')], help_text='Необходимо указать.', null=True, verbose_name='Тип скидки'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Укажите оценку'), (5, 'Великолепно'), (4, 'Хорошо'), (3, 'Обычно'), (2, 'Плохо'), (1, 'Ужасно')], help_text='Здесь Вы можете указать вашу оценку', null=True, verbose_name='Ваша оценка'),
        ),
    ]
