# Generated by Django 4.1.2 on 2022-10-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_visit_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='service',
        ),
        migrations.AlterField(
            model_name='visit',
            name='service_price',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Укажите услугу'), (1000, 'Маникюр'), (2000, 'Маникюр с покрытием'), (2800, 'Коррекция'), (3800, 'Наращивание'), (2500, 'Френч'), (2600, 'Педикюр'), (3000, 'Педикюр с покрытием (стопа)'), (2300, 'Педикюр с покрытием (пальчики)')], help_text='Выберите тип услуги', verbose_name='Тип услуги'),
        ),
    ]
