# Generated by Django 4.1.2 on 2022-11-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_calendar_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='master',
            field=models.ForeignKey(help_text='Укажите зарегистрированного мастера', on_delete=django.db.models.deletion.CASCADE, to='services.master', to_field='user_id', verbose_name='Мастер'),
        ),
    ]
