# Generated by Django 4.1.2 on 2022-10-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_visit_discount_alter_visit_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_phone_number',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[(None, 'Укажите тип клиента'), ('Постоянный клиент', 'Постоянный клиент'), ('Обычный клиент', 'Обычный клиент'), ('Первый визит', 'Первый визит')], help_text='Введите тип клиента', max_length=20, verbose_name='Тип клиента'),
        ),
    ]
