# Generated by Django 4.1.2 on 2022-11-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_calendar_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visit',
            new_name='calendar',
        ),
    ]
