# Generated by Django 4.1.2 on 2022-10-15 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_discount_delete_service_user_is_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(help_text='Выберите зарегистрированного пользователя', limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(help_text='Укажите зарегистрированного пользователя', limit_choices_to={'is_client': False, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь должен считаться клиентом.', verbose_name='Клиент'),
        ),
    ]
