# Generated by Django 4.1.2 on 2022-10-15 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_client_user_alter_master_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(help_text='Укажите зарегистрированного пользователя', limit_choices_to={'is_client': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='discount',
            field=models.FloatField(blank=True, choices=[(None, 'Укажите скидку'), (0.15, 'Первый визит'), (0.35, 'Шестой визит'), (500.0, 'Сарафан')], help_text='Необходимо указать.', null=True, verbose_name='Тип скидки'),
        ),
    ]
