# Generated by Django 4.1.2 on 2022-11-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_visit_unique_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='calendar',
            field=models.OneToOneField(help_text='Необходимо указать. Укажите дату и время записи', limit_choices_to={'is_free': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.calendar', verbose_name='Дата и время записи'),
        ),
    ]
