# Generated by Django 4.1.2 on 2022-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_visit_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_visit_manicure',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата последнего маникюра'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_visit_pedicure',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата последнего педикюра'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[(None, 'Выберите тип записи'), ('Предварительная запись', 'Предварительная запись'), ('Успешная запись', 'Успешная запись'), ('Отмененная запись', 'Отмененная запись')], default='Предварительная запись', help_text='Необходимо указать.', max_length=30, verbose_name='Тип записи'),
        ),
    ]
