# Generated by Django 4.1.2 on 2022-12-12 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_client_last_visit_manicure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_type',
            field=models.CharField(choices=[(None, 'Укажите тип клиента'), ('Постоянный клиент', 'Постоянный клиент'), ('Первый визит', 'Первый визит')], default='Первый визит', help_text='Введите тип клиента', max_length=20, verbose_name='Тип клиента'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='discount',
            field=models.DecimalField(blank=True, choices=[(None, 'Укажите скидку'), (Decimal('0.15'), 'Первый визит'), (Decimal('500.00'), 'Сарафан')], decimal_places=2, default=None, help_text='Необходимо указать.', max_digits=5, null=True, verbose_name='Тип скидки'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[(None, 'Выберите тип записи'), ('Предварительная запись', 'Предварительная запись'), ('Успешная запись', 'Успешная запись')], default='Предварительная запись', help_text='Необходимо указать.', max_length=30, verbose_name='Тип записи'),
        ),
    ]
