# Generated by Django 4.1.2 on 2022-12-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_client_user_type_alter_visit_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='calendar',
            field=models.OneToOneField(blank=True, help_text='Необходимо указать. Укажите дату и время записи', limit_choices_to={'is_free': True}, on_delete=django.db.models.deletion.PROTECT, to='services.calendar', verbose_name='Дата и время записи'),
        ),
    ]
