# Generated by Django 4.1.2 on 2022-12-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_visit_discount_alter_visit_extra_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['user__last_name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
