# Generated by Django 4.1.2 on 2022-12-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[(None, 'Выберите тип записи'), ('Предварительная запись', 'Предварительная запись'), ('Успешная запись', 'Успешная запись')], db_index=True, default='Предварительная запись', help_text='Необходимо указать.', max_length=30, verbose_name='Тип записи'),
        ),
    ]
