# Generated by Django 4.1.2 on 2022-12-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(help_text='Необходимо указать.', on_delete=django.db.models.deletion.PROTECT, to='services.client', verbose_name='Клиент'),
        ),
    ]
