# Generated by Django 4.1.2 on 2022-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_visit_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['date_time'], 'verbose_name': 'Календарь', 'verbose_name_plural': 'Календарь'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Запись свободна'),
        ),
    ]
