# Generated by Django 4.1.2 on 2022-12-26 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0018_alter_calendar_options_alter_calendar_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(help_text='Выберите зарегистрированного пользователя', limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='phone_number', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(help_text='Укажите зарегистрированного пользователя', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='phone_number', verbose_name='Мастер'),
        ),
    ]
