# Generated by Django 4.1.2 on 2022-12-27 12:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_visit_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='discount',
            field=models.DecimalField(blank=True, choices=[(None, 'Укажите скидку'), (Decimal('0.15'), 'Первый визит'), (Decimal('0.35'), 'Шестой визит'), (Decimal('500.00'), 'Сарафан')], decimal_places=2, default=None, help_text='Необходимо указать.', max_digits=5, null=True, verbose_name='Тип скидки'),
        ),
    ]
