# Generated by Django 4.1.2 on 2022-10-14 08:04

from django.db import migrations, models
import django.db.models.deletion
import services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким номером телефона уже существует.'}, help_text="Обязательно. Максимально допустимое кол-во символов - 18. Цифры и символы '()', '+' и '_'.", max_length=150, unique=True, validators=[services.validators.PhoneNumberValidator()], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='master',
            field=models.ForeignKey(help_text='Укажите мастера', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Укажите оценку'), (5, 'Великолепно'), (4, 'Хорошо'), (3, 'Обычно'), (2, 'Плохо'), (1, 'Ужасно')], help_text='Здесь Вы можете указать вашу оценку', null=True, unique=True, verbose_name='Ваша оценка'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service',
            field=models.ForeignKey(help_text='Выберите тип услуги', on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[(None, 'Выберите тип записи'), ('Предварительная запись', 'Предварительная запись'), ('Успешная запись', 'Успешная запись'), ('Отмененная запись', 'Отмененная запись')], help_text='Выберите тип записи', max_length=30, verbose_name='Тип записи'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(help_text='Укажите дату и время записи', unique=True, verbose_name='Дата и время записи'),
        ),
    ]
