# Generated by Django 4.1.2 on 2022-10-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_user_options_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='discount',
            field=models.FloatField(choices=[(None, 'Укажите скидку'), (0.15, 'Первый визит'), (0.35, 'Шестой визит'), (500.0, 'Сарафан')], help_text='Выберите тип скидки', verbose_name='Тип скидки'),
        ),
    ]
