# Generated by Django 4.1.2 on 2022-10-14 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_visit_service_alter_visit_service_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, help_text="Указать, будет ли данный пользователь иметь статус 'Клиент'", verbose_name="Клиент'"),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[(None, 'Укажите пользователя'), ('Постоянный клиент', 'Постоянный клиент'), ('Обычный клиент', 'Обычный клиент'), ('Первый визит', 'Первый визит')], help_text='Введите тип клиента', max_length=20, verbose_name='Тип клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(help_text='Выберите зарегистрированного пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='master',
            name='qualification',
            field=models.CharField(blank=True, choices=[(None, 'Укажите квалификалицию мастера'), ('Топ-мастер', 'Топ-мастер'), ('Обычный мастер', 'Обычный мастер'), ('Ученик', 'Ученик')], help_text='Выберите квалификалицию мастера', max_length=15, null=True, verbose_name='Квалификация мастера'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(help_text='Необходимо указать.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='discount',
            field=models.FloatField(choices=[(None, 'Укажите скидку'), (0.15, 'Первый визит'), (0.35, 'Шестой визит'), (500.0, 'Сарафан')], help_text='Необходимо указать.', verbose_name='Тип скидки'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='master',
            field=models.ForeignKey(help_text='Необходимо указать.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service_price',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Укажите услугу'), (1000, 'Маникюр'), (2000, 'Маникюр с покрытием'), (2800, 'Коррекция'), (3800, 'Наращивание'), (2500, 'Френч'), (2600, 'Педикюр'), (3000, 'Педикюр с покрытием (стопа)'), (2300, 'Педикюр с покрытием (пальчики)')], help_text='Необходимо указать.', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[(None, 'Выберите тип записи'), ('Предварительная запись', 'Предварительная запись'), ('Успешная запись', 'Успешная запись'), ('Отмененная запись', 'Отмененная запись')], help_text='Необходимо указать.', max_length=30, verbose_name='Тип записи'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(help_text='Необходимо указать. Укажите дату и время записи', unique=True, verbose_name='Дата и время записи'),
        ),
    ]
