version: "3"

volumes:
  postgres_volume:
  static_volume:

services:

  # telegram_bot:
  #   container_name: telegram_bot
  #   build: ../telebot/
  #   restart: unless-stopped
  #   env_file:
  #     - ./../.env
  #   depends_on:
  #     - db
  #   networks:
  #     main:

  db:
    container_name: postgresql_db
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - ./../.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      main:
    ports:
      - "5433:5432"

  # web:
  #   container_name: artsoul_main
  #   build: ../backend/
  #   restart: unless-stopped
  #   volumes:
  #     - static_volume:/usr/src/app/staticfiles
  #   expose:
  #     - 8000
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./../.env
  #   networks:
  #       main:
  #           aliases:
  #               - web

  # nginx:
  #   build: ../nginx/debug
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
  #   volumes:
  #     - static_volume:/usr/src/app/staticfiles
  #   networks:
  #       main:
  #           aliases:
  #               - web

networks:
  main:
