version: "3"

volumes:
  postgres_volume:
  static_volume:
  backend:

services:

  telegram_bot:
    container_name: telegram_bot
    build: ../telebot/
    restart: unless-stopped
    env_file:
      - ./../.env
    depends_on:
      - web
    networks:
      main:

  nginx:
    build: ../nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - backend:/usr/share/nginx/html
    networks:
        main:
            aliases:
                - web

  db:
    container_name: postgresql_db
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=artsoul
      - POSTGRES_PASSWORD=porosenok0211
      - POSTGRES_DB=artsoul
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      main:
    ports:
      - "5433:5432"

  web:
    container_name: artsoul_main
    build: ../backend/
    restart: unless-stopped
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - backend:/usr/src/app
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./../.env
    networks:
        main:
            aliases:
                - web

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  main:
